pages/config/routes.rb
Refinery::Core::Engine.routes.draw do
  root :to => 'pages#home', :via => :get
  get '/pages/:id', :to => 'pages#show', :as => :page

  namespace :pages, :path => '' do
    namespace :admin, :path => Refinery::Core.backend_route do
      scope :path => :pages do
        post 'preview', :to => 'preview#show', :as => :preview_pages
        put  'preview/*path', :to => 'preview#show', :as => :preview_page
      end
    end
  end

  namespace :admin, :path => Refinery::Core.backend_route do
    get 'pages/*path/edit', :to => 'pages#edit'
    get 'pages/*path/children', :to => 'pages#children', :as => 'children_pages'
    put 'pages/*path', :to => 'pages#update'
    delete 'pages/*path', :to => 'pages#destroy'

    resources :pages, :except => :show do
      post :update_positions, :on => :collection
    end

    resources :pages_dialogs, :only => [] do
      collection do
        get :link_to
      end
    end

    resources :page_parts, :only => [:new, :create, :destroy]
  end
end

pages/app/views/refinery/admin/pages/_actions.html.erb
<ul>
  <li>
    <%= render '/refinery/admin/search', :url => refinery.admin_pages_path %>
  </li>
  <li>
    <%= link_to t('.create_new_page'), refinery.new_admin_page_path,
                :class => "add_icon" %>
  </li>
<% if @pages.many? and !searching? %>
  <li>
    <%= link_to t('.reorder_pages'), refinery.admin_pages_path,
                :id => "reorder_action",
                :class => "reorder_icon" %>

    <%= link_to t('.reorder_pages_done'), refinery.admin_pages_path,
                :id => "reorder_action_done",
                :style => "display: none;",
                :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

pages/app/views/refinery/admin/pages/_form.html.erb
<%= form_for [refinery, :admin, @page],
             :url => (refinery.admin_page_path(@page.nested_url) if @page.persisted?) do |f| %>

  <%= render '/refinery/admin/error_messages', :object => @page, :include_object_name => true %>

  <%= render '/refinery/admin/locale_picker', :current_locale => Globalize.locale %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "larger widest" %>
  </div>

  <%= render 'form_fields_after_title', :f => f %>

  <div class='field'>
    <%= render 'form_page_parts', :f => f %>
  </div>

  <%= render 'form_advanced_options', :f => f %>

  <%= render '/refinery/admin/form_actions', :f => f,
             :continue_editing => true,
             :delete_title => t('delete', :scope => 'refinery.admin.pages'),
             :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => @page.title),
             :before_cancel_button => submit_tag(
               t('.preview'),
               :id => 'preview-button',
               :title => 'Preview page',
               :name => nil,
               :class => "wymupdate button",
               :tooltip => t('.preview_changes')
             ),
             :cancel_url => refinery.admin_pages_path %>

  <%= render 'form_new_page_parts', :f => f if Refinery::Pages.new_page_parts %>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      page_options.init(
        <%= Refinery::Pages.new_page_parts.to_s %>
        , "<%= refinery.new_admin_page_part_path %>"
        , "<%= refinery.admin_page_parts_path %>"
      );

      $("#preview-button").click(function(e) {
        var form = $(this).parents('form');
        var prev_url = form.attr('action');
        var prev_target = form.attr('target');
        form.attr({
          'action': '<%= @page.persisted? ? refinery.pages_admin_preview_page_path(@page.nested_url) : refinery.pages_admin_preview_pages_path %>'
          , 'target': '_blank'
        });
        form.submit();
        form.attr({
          'action': prev_url
          , 'target': prev_target
        });
        e.preventDefault();
      });
    });
  </script>
<% end %>

pages/app/views/refinery/admin/pages/_form_advanced_options.html.erb
<%= render '/refinery/admin/form_advanced_options_menu', :f => f %>

<div id="more_options" style="display:none;">
  <div class="hemisquare">
    <h2><%= t('.page_options') %></h2>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :parent_id, t('.parent_page') %>
        <%= refinery_help_tag t('.parent_page_help') %>
      </span>
      <%= f.select :parent_id, parent_id_nested_set_options(@page), :include_blank => true %>
    </div>
    <% if Refinery::Pages.use_layout_templates %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :layout_template, t('.layout_template') %>
        <%= refinery_help_tag t('.layout_template_help') %>
      </span>
      <%= f.select :layout_template, @valid_layout_templates,
                   template_options(:layout_template, @page) %>
    </div>
    <% end %>
    <% if Refinery::Pages.use_view_templates %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :view_template, t('.view_template') %>
        <%= refinery_help_tag t('.view_template_help') %>
      </span>
      <%= f.select :view_template, @valid_view_templates.map { |t| [t.titleize, t] },
                   template_options(:view_template, @page) %>
    </div>
    <% end %>

    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :menu_title, t('.menu_title') %>
        <%= refinery_help_tag t('.menu_title_help') %>
      </span>
      <%= f.text_field :menu_title, :style=> 'width:400px;' %>
    </div>
    <% if Refinery::Pages.use_custom_slugs %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :custom_slug, t('.custom_slug') %>
        <%= refinery_help_tag t('.custom_slug_help') %>
      </span>
      <%= f.text_field :custom_slug, :style=> 'width:400px;' %>
    </div>
    <% end %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :skip_to_first_child?, t('.skip_to_first_child') %>
        <%= refinery_help_tag t('.skip_to_first_child_help') %>
      </span>
      <%= f.check_box :skip_to_first_child %>
      <%= f.label :skip_to_first_child, t('.skip_to_first_child_label'),
                  :class => "stripped" %>
    </div>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :link_url, t('.link_url') %>
        <%= refinery_help_tag t('.link_url_help') %>
      </span>
      <%= f.text_field :link_url, :style=> 'width:400px;' %>
      <% content_for :javascripts do %>
      <script>
        $(document).ready(function(){
          link_tester.validate_url_textbox("#page_link_url")
        });
      </script>
      <% end %>
    </div>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :show_in_menu, t('.show_in_menu_title'),
                    :id => 'page_show_in_menu_heading' %>
        <%= refinery_help_tag t('.show_in_menu_help') %>
      </span>
      <%= f.check_box :show_in_menu %>
      <%= f.label :show_in_menu, t('.show_in_menu_description'),
                  :class => "stripped" %>
    </div>
  </div>

  <%= render 'form_advanced_options_seo', :f => f %>
</div>

pages/app/views/refinery/admin/pages/_form_advanced_options_seo.html.erb
<div class="hemisquare right_side">
  <%= render '/seo_meta/form', :form => f %>
</div>

pages/app/views/refinery/admin/pages/_form_fields_after_title.html.erb
<%# Intentionally empty, useful override point to add extra fields. %>

pages/app/views/refinery/admin/pages/_form_new_page_parts.html.erb
<div id='new_page_part_dialog' style='display: none'>
  <div class='field'>
    <label for='new_page_part_title'><%= t('.title')  %></label>
    <input id='new_page_part_title' value='' class='larger widest' />
    <input id='new_page_part_index' type='hidden' value='<%= @page.parts.size %>' />
  </div>
  <%= render '/refinery/admin/form_actions', :f => f,
             :continue_editing => false,
             :submit_button_id => "new_page_part_save",
             :cancel_button_id => "new_page_part_cancel",
             :hide_delete => true %>
</div>

pages/app/views/refinery/admin/pages/_page.html.erb
<li class='clearfix record icons' id="<%= dom_id(page) -%>">
  <div class='clearfix'>
    <% if page.children.present? %>
      <span class="icon toggle <%= 'expanded' if Refinery::Pages.auto_expand_admin_tree %>" title="<%= t('expand_collapse', :scope => 'refinery.admin.pages') %>"></span>
    <% else %>
      <span class="icon"></span>
    <% end %>

    <span class='title <%= 'toggle' if page.children.present? %>'>
      <%= page_title_with_translations page %>
      <%= page_meta_information page %>
    </span>
    <% if Refinery::I18n.frontend_locales.many? %>
      <span class='locales'>
        <% page.translations.sort_by{|t| Refinery::I18n.frontend_locales.index(t.locale)}.each do |translation| %>
          <%= link_to refinery_icon_tag("flags/#{translation.locale}.png", :size => '16x11'),
                      refinery.edit_admin_page_path(page.nested_url, :switch_locale => translation.locale),
                      :class => 'locale' if translation.title.present? %>
        <% end %>
      </span>
    <% end %>

    <span class='actions'>
      <%= link_to refinery_icon_tag('application_go.png'),
                  page.url,
                  :target => "_blank",
                  :title => t('.view_live_html') %>
      <%= link_to refinery_icon_tag('page_add.png'),
                  refinery.new_admin_page_path(:parent_id => page.id),
                  :title => t('new', :scope => 'refinery.admin.pages') %>

      <%= link_to refinery_icon_tag('application_edit.png'),
                  refinery.edit_admin_page_path(page.nested_url, :switch_locale => (page.translations.first.locale unless page.translated_to_default_locale?)),
                  :title => t('edit', :scope => 'refinery.admin.pages') %>

      <%= link_to refinery_icon_tag('delete.png'),
                  refinery.admin_page_path(page.nested_url),
                  :class => "cancel confirm-delete",
                  :title => t('delete', :scope => 'refinery.admin.pages'),
                  :data => {
                    :confirm => t('message',
                      :scope => 'refinery.admin.delete',
                      :title => page_title_with_translations(page)
                    )
                  },
                  :method => :delete if page.deletable? %>
    </span>
  </div>
  <ul class='nested' data-ajax-content="<%= refinery.admin_children_pages_path(page.nested_url) %>">
    <%= render(:partial => 'page', :collection => page.children) if Refinery::Pages.auto_expand_admin_tree %>
  </ul>
</li>

pages/app/views/refinery/admin/pages/_page_part_field.html.erb
<div class='page_part' id='<%= new_part ? "page_part_new_#{part_index}" : part.to_param %>'>
  <%= hidden_field_tag "page[parts_attributes][#{part_index}][title]", part.title if new_part %>
  <%= text_area_tag "page[parts_attributes][#{part_index}][body]", part.body, :rows => 20, :class => 'wymeditor widest' %>
  <%= hidden_field_tag "page[parts_attributes][#{part_index}][position]", part_index %>
</div>

pages/app/views/refinery/admin/pages/_save_and_continue_callback.html.erb
<%= render '/refinery/message' %>
<%= hidden_field_tag 'new_action', local_assigns[:new_refinery_page_path] %>
<script>refinery_page_preview_url = '<%= local_assigns[:new_page_path] %>';</script>

pages/app/views/refinery/admin/pages/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'page', :collection => @pages.roots  %>
</ul>
<%= render '/refinery/admin/sortable_list', :continue_reordering => !!local_assigns[:continue_reordering] %>

pages/app/views/refinery/admin/pages/children.html.erb
<%= render :partial => 'page', :collection => @page.children %>

pages/app/views/refinery/admin/pages/edit.html.erb
<%= render 'form' %>

pages/app/views/refinery/admin/pages/index.html.erb
<section id='records' class='tree'>
  <% cache_if(Refinery::Pages.cache_pages_backend, [Refinery::Core.base_cache_key, "pages_backend", Globalize.locale].join('_')) do %>
    <%= render 'records' %>
  <% end %>
</section>
<section id='actions'>
  <%= render 'actions' %>
</section>
<%= render '/refinery/admin/make_sortable', :tree => true, :replace_contents_after_update => true if @pages.many? -%>

pages/app/views/refinery/admin/pages/new.html.erb
<%= render 'form' %>